version: "3.3"
    
services:
  db:
    image: mariadb:10.3
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: somewordpress
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
    depends_on:
      - db
    
  wordpress:
    depends_on:
      - db
    image: wordpress:5.9
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: in22_
volumes:
  db_data: {}

